sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v3.0.0/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build image
- docker build -t ctt828/arm32v6 .
# test image
- docker run ctt828/arm32v6 uname -a
# push image
- docker push ctt828/arm32v6 -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
